### ISSUE TITLE
PMS Idle Power Draw

### ISSUE THREAD

**Issue by thejimster82** [UVA-DSI/sensenet#3]
The Feather M0 LoRa draws about 0.37mA of current in idle. When the PMS is connected and the RESET held high, it runs at 1.7mA. If we could instead disconnect power from the PMS entirely using a MOSFET or BJT, we might be able to save that little bit of power and significantly increase the battery life of the device.

**Comment by unixjazz** [comment]
Works as designed: the solution where would be to pick a low-power sensor.
