### ISSUE TITLE
Optimal LoRa Radio Settings

### ISSUE THREAD

**Issue by thejimster82** [UVA-DSI/sensenet#4]
Right now, the LoRa radio reaches 130mA of current when sending packets. It is possible to change the parameters on the radio in a way that might reduce this current draw, especially in the circumstance that the user is very close to their gateway.

**Comment by unixjazz** [comment]
If the sensor box is closer to the gateway, the LMIC library allows for changing the TX power:
```
    // Set the transmission power (0 - 14):
    LMIC_setDrTxpow(DR_SF7, 0);
```
